DROP DATABASE IF EXISTS user;

DROP DATABASE IF EXISTS invoice;

DROP DATABASE IF EXISTS report;

CREATE DATABASE IF NOT EXISTS user;

CREATE DATABASE IF NOT EXISTS invoice;

CREATE DATABASE IF NOT EXISTS report;